module Emit

open System
open System.IO
open System.Text
open Hash
open Model

/// Indentation-aware source writer.
type private Writer() =
    let sb = StringBuilder()
    let mutable padding = 0

    member _.Line(line: string) =
        sb.Append(' ', padding).AppendLine(line) |> ignore

    member _.Blank() = sb.AppendLine() |> ignore

    member _.Indent() = padding <- padding + 4

    member _.Unindent() = if padding >= 4 then padding <- padding - 4

    override _.ToString() = sb.ToString()

let private escapeLiteral (value: string) =
    let sb = StringBuilder(value.Length)

    for c in value do
        match c with
        | '\\' -> sb.Append("\\\\") |> ignore
        | '"' -> sb.Append("\\\"") |> ignore
        | '\n' -> sb.Append("\\n") |> ignore
        | '\r' -> sb.Append("\\r") |> ignore
        | '\t' -> sb.Append("\\t") |> ignore
        | c when int c < 0x20 -> sb.Append("\\u").Append((int c).ToString("x4")) |> ignore
        | c -> sb.Append(c) |> ignore

    sb.ToString()

let private quote (value: string) = "\"" + escapeLiteral value + "\""

let generateTranslations (db: Database) : string =
    let w = Writer()

    w.Line "// <auto-generated>This file was generated by the SFD.Scripting.MapTranslationProject generator. Do not edit manually.</auto-generated>"
    w.Blank()
    w.Line "namespace SFD.Scripting.MapTranslationProject;"
    w.Blank()
    w.Line "public partial class GameScript : GameScriptInterfaceExtended"
    w.Line "{"
    w.Indent()
    w.Line "internal static class TranslationsDatabase"
    w.Line "{"
    w.Indent()

    let codes =
        db.Languages
        |> List.map (fun l -> quote l.Code)
        |> String.concat ", "

    let displayNames =
        db.Languages
        |> List.map (fun l -> quote l.DisplayName)
        |> String.concat ", "

    w.Line $"public static readonly string[] LanguageCodes = {{ {codes} }};"
    w.Line $"public static readonly string[] LanguageDisplayNames = {{ {displayNames} }};"
    w.Blank()

    let dictionaryType =
        "Dictionary<string, Dictionary<string, Dictionary<ulong, string>>>"

    w.Line $"public static readonly {dictionaryType} Maps = new()"
    w.Line "{"
    w.Indent()

    for map in db.Maps |> List.sortBy (fun m -> m.Guid) do
        w.Line $"[{quote map.Guid}] = new()"
        w.Line "{"
        w.Indent()

        let keyToEntry = map.Entries |> List.map (fun e -> e.Key, e) |> Map.ofList

        // Map iteration order is key-sorted, giving deterministic output.
        for language, table in Map.toList map.Translations do
            w.Line $"[{quote language}] = new()"
            w.Line "{"
            w.Indent()

            table
            |> Seq.filter (fun kv -> kv.Value <> "")
            |> Seq.choose (fun kv ->
                Map.tryFind kv.Key keyToEntry
                |> Option.map (fun entry ->
                    (compute (Kind.tag entry.Kind) entry.Original, kv.Value)))
            |> Seq.sortBy fst
            |> Seq.iter (fun (hash, translation) ->
                w.Line $"[{toLiteral hash}] = {quote translation},")

            w.Unindent()
            w.Line "},"

        w.Unindent()
        w.Line "},"

    w.Unindent()
    w.Line "};"
    w.Unindent()
    w.Line "}"
    w.Unindent()
    w.Line "}"

    w.ToString()

/// Writes the generated source to disk as UTF-8 without a BOM.
let writeGenerated (path: string) (source: string) : unit =
    Directory.CreateDirectory(Path.GetDirectoryName path) |> ignore
    File.WriteAllText(path, source, UTF8Encoding(false))
